'use client';
export const ActionTypes={
     GET_STUDENT:"GET_STUDENT",
     ADD_STUDENT:"ADD_STUDENT",
     ADD_NEW_STUDENT:"ADD_NEW_STUDENT",
     UPDATE_STUDENT:"UPDATE_STUDENT",
     DELETE_STUDENT:"DELETE_STUDENT"
}